name: Tweet daily from tweet queue
'on':
  push:
    branches:
      - master
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - name: Tweet From Queue
        env:
          DRIVE_AUTH_TOKEN_PATH: ${{ secrets.DRIVE_AUTH_TOKEN_PATH }}
          GMAIL_ID: ${{ secrets.GMAIL_ID }}
          GMAIL_SECRET: ${{ secrets.GMAIL_SECRET }}
          SER_ACCESS_SECRET: ${{ secrets.SER_ACCESS_SECRET }}
          SER_ACCESS_TOKEN: ${{ secrets.SER_ACCESS_TOKEN }}
          SER_CONSUMER_KEY: ${{ secrets.SER_CONSUMER_KEY }}
          SER_CONSUMER_SECRET: ${{ secrets.SER_CONSUMER_SECRET }}
          TWITTER_APP_NAME: ${{ secrets.TWITTER_APP_NAME }}
        run: |-
          Rscript -e "library(ser); source_ser('test_email_error'); source_ser('test_email_summary')"
    container: rocker/verse:latest
